import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const outDir = join(root, "public", "fonts");
mkdirSync(outDir, { recursive: true });

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..900;1,9..144,300..900&family=Inter:ital,wght@0,300..700;1,300..700&display=swap";
const LATIN_RANGE = /U\+0000-00FF/;

async function fetchCss(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`CSS fetch failed: ${res.status}`);
  return res.text();
}

async function download(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Font fetch failed ${res.status}: ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

function weightKind(weightStr) {
  if (/^\d+ \d+$/.test(weightStr)) return { label: "variable", range: weightStr };
  return { label: weightStr, range: weightStr };
}

async function main() {
  const css = await fetchCss(CSS_URL);
  const blocks = css.split("@font-face").filter((b) => b.includes("src:"));
  const faces = [];
  const seen = new Set();

  for (const block of blocks) {
    if (!LATIN_RANGE.test(block)) continue;

    const url = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1];
    if (!url || seen.has(url)) continue;
    seen.add(url);

    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? "normal";
    const weightRaw = (block.match(/font-weight:\s*([^;]+);/) ?? [null, "400"])[1].trim();
    const { label, range } = weightKind(weightRaw);

    const slug = family.toLowerCase().replace(/\s+/g, "");
    const filename = `${slug}-${label}-${style}.woff2`;

    const buf = await download(url);
    writeFileSync(join(outDir, filename), buf);
    faces.push({
      family,
      style,
      weight: range,
      localPath: `/fonts/${filename}`,
      bytes: buf.length,
    });
    console.log(`  ${filename}  ${(buf.length / 1024).toFixed(1)} KiB`);
  }

  const header = `/* Generated by scripts/gen-fonts.mjs. */

`;
  const fontFaces = faces
    .map(
      (f) =>
        `@font-face {\n  font-family: '${f.family}';\n  font-style: ${f.style};\n  font-weight: ${f.weight};\n  font-display: swap;\n  src: url('${f.localPath}') format('woff2');\n  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+20AC, U+2122, U+2191, U+2193;\n}`
    )
    .join("\n\n");

  writeFileSync(join(root, "src", "fonts.css"), `${header}${fontFaces}\n`);
  writeFileSync(join(root, "scripts", ".fonts-manifest.json"), JSON.stringify(faces, null, 2));
  console.log(`\nWrote ${faces.length} @font-face rules → src/fonts.css`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});